config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  devise_for :users

  root 'store#index'

  # store controller
  get '/store/:id', to: 'store#show', as: 'detail'
  get 'under_construction', to: 'store#under_construction', as: "not_implemented"


  # Dashboard
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  # product routes
  resources :products
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :order_products
    has_many :products, through: :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders

  enum role: {
    guest: 0,
    client: 1,
    admin: 2
  }

  after_initialize do
    if self.new_record?
      self.role ||= :guest
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
    end

    private 

    def user_not_authorized
        redirect_to root_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  layout 'layouts/backstage'
  before_action :authenticate_user!
  
  def index
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!
    layout 'layouts/backstage'

    def index
        @products = Product.all
        authorize Product
    end

    def new
        @product = Product.new
    end

    def edit
        @product = Product.find(params[:id])
    end

    def show
        redirect_to products_path
    end

    def create
        @product = Product.create product_params
        redirect_to products_path
    end

    def update
        @product = Product.find(params[:id])
        @product.update product_params
        redirect_to products_path
    end

    def destroy
        puts "\n\n\n-------Destroy\n----------"
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end


    private

    def product_params
        params.require(:product).permit(:name, :description, :price, :stock, :available)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @products = Product.where.not(id: params[:id])
  end

  def under_construction
    render file: 'public/404.html', layout: false, status: :not_found
  end

  def cart
  end

  def add_to_cart
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
            controller.render(opntions.merge(formats: :html))
            rescue ActionView::MissingTemplate => :error
                if get?
                    raise error
                elsif has_errors? && default_action
                    render rendering_options.merge(formats: :html, status: :unprocessable_entity)
                else
                    redirect_to navigation_location
                end
        end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buonaduona</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Lemon&family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rye&display=swap" rel="stylesheet">
  </head>

  <body>
  <!-- Inicia navegación -->
    <nav class="navbar   justify-content-end navbar-expand-lg">
        <div class="container-fluid ">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag "logoBD.png", class: "logo d-none d-md-block d-lg-block d-xl-block" %>
            <span class="letras d-block d-sm-block d-md-none d-lg-none d-xl-none">Buona Duona</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><i class="bi bi-three-dots-vertical"></i></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent" >
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: 'nav-link active', aria: { current: 'page' } %>
              </li>
              <li class="nav-item">
                <%= link_to "Repostería", not_implemented_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Café", not_implemented_path, class: 'nav-link' %>
              </li>
              
              <li class="nav-item" type="submit" style="margin-right: 1em"> 
                <%= link_to "Shopping bag", not_implemented_path, class: 'nav-link d-inline-block' %><i class="bi bi-bag-heart"></i>
              </li> 
              
            
              <li class="nav-item dropdown ml-5" type="submit"> 
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Cuenta <i class="bi bi-person-circle"></i></a>

                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <% if user_signed_in? %>
                    <% if current_user.admin? %>
                      <li><%= link_to "Panel", dashboard_path, class: "dropdown-item text-black" %></li>
                      <li><hr class="dropdown-divider"></li>
                    <% end %>
                    <li><%= link_to "Salir", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-black" %></li>
                  <% else %>
                    <li><%= link_to "Iniciar sesión", new_user_session_path, class: "dropdown-item text-black" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Registrarse", new_user_registration_path, class: "dropdown-item text-black" %></li>
                  <% end %>
                  <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                </ul>
              </li> 
            
              
              
            </ul>
            <%# <form class="d-flex" role="search">
            
             
              
              <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Barra de búsqueda">
              <button class="btn " type="submit"><i class="bi bi-search"></i></button>
            </form> %>
            <%= form_with url: not_implemented_path, class: 'd-flex', role:'search' do |f| %>
                <%= f.search_field :product_name, placeholder: "Buscar", class:"form-control me-2", aria: { label: "Barra de búsqueda" } %>
                <%= button_to '', class: 'btn' do %><i class="bi bi-search"></i><% end %>
            <%end%>
          </div>
        </div>
      </nav>

<!-- Fin de la navegación -->

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>

    <footer>
      <br><br>
      <p class="pie-pagina">Derechos reservados</p>
    </footer>
  </body>
</html>

app/views/layouts/backstage.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Lemon&family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rye&display=swap" rel="stylesheet">
    <title>Panel de administración</title>
</head>
<body style="background-color: #eeeeee">
    

    <div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto px-0">
            <div id="sidebar" class="collapse collapse-horizontal show border-end">
                <div id="sidebar-nav" class="list-group border-0 rounded-0 text-sm-start min-vh-100">
                    <%# <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-bootstrap"></i> <span>Item</span> </a> %>
                    <%= link_to 'Ir al sitio', '/', class: 'list-group-item border-end-0 d-inline-block text-truncate', "data-bs-parent" => '#sidebar' %>
                    <%= link_to 'Dashboard', dashboard_path, class: 'list-group-item border-end-0 d-inline-block text-truncate', "data-bs-parent" => '#sidebar' %>
                    <%= link_to 'Productos', products_path, class: 'list-group-item border-end-0 d-inline-block text-truncate', "data-bs-parent" => '#sidebar'  %>
                    <%= link_to 'Pedidos', '#', class: 'list-group-item border-end-0 d-inline-block text-truncate', "data-bs-parent" => '#sidebar'  %>
                </div>
            </div>
        </div>
        <main class="col ps-md-2 pt-2">
            <a href="#" data-bs-target="#sidebar" data-bs-toggle="collapse" class="border rounded-3 p-1 text-decoration-none"><i class="bi bi-list bi-lg py-2 p-1"></i> Menu</a>
            <div class="row">
                <div class="col-12">
                   <%= yield %>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>

app/views/partials/_edit_product.html.erb
<%= form_with model: @product do |f|%>
    <%= f.label :name, 'Nombre:'%>              <br>
    <%= f.text_field :name %>                   <br>
    <%= f.label :description, 'Descripción:'%>  <br>
    <%= f.text_area :description %>            <br>
    <%= f.label :price, 'Precio:'%>             <br>
    <%= f.text_field :price %>                  <br>
    <%= f.label :stock, 'Stock disponible:'%>   <br>
    <%= f.number_field :stock, id: 'stock'%>    <br>
    <%= f.label :available, 'Disponible:'%>     <br>
    <%= f.check_box :available, id: 'available' %><br>
    <%= f.submit "Guardar"%>
<% end %>

<script>
    var stock = document.getElementById('stock');
    var available = document.getElementById('available');

    stock.addEventListener('change', function () {
        available.checked = (parseInt(stock.value) > 0)? true : false;
    });
</script>

app/views/partials/_index_products.html.erb
<% @products.each do |p| %>
<p>
    <strong><%= p.name %></strong><br>
    <%= p.description %><br>
    <span>Precio: $<%= p.price %></span>
    <%= link_to 'Comprar', detail_path(p.id) %>
</p>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<%= render partial: 'partials/edit_product' %>

app/views/products/index.html.erb
<h1>Products#index</h1>

<%= link_to 'Agregar nuevo', new_product_path %>
<% @products.each do |p| %>
<p>
    <strong><%= p.name %></strong><br>
    <%= p.description %><br>
    <span>Precio: $<%= p.price %></span><br>
    <span>Stock disponible: <%= p.stock %> unidades</span><br>
    <%= link_to 'Editar', edit_product_path(p.id) %>
    <%= link_to 'Eliminar', product_path(p), data: { turbo_method: :delete }%>
</p>
<% end %>

app/views/products/new.html.erb
<h1>Products#new</h1>
<%= render partial: 'partials/edit_product' %>

app/views/store/cart.html.erb
<h1>Store#cart</h1>
<p>Find me in app/views/store/cart.html.erb</p>

app/views/store/index.html.erb
    <main>
      <!-- Inicia carrusel promocional -->
              <div id="carouselExampleCaptions" class="carousel slide d-none d-sm-none d-md-block d-lg-block d-xl-block" data-bs-ride="false">
                  <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                  </div>
                  <div class="carousel-inner ">
                    
                    <div class="carousel-item active" data-bs-interval="4000">
                      <%# <img src="img/promo01_1.jpg" class="d-block w-100" alt="Imagen de promocional paquete de panques"aria-label="Imagen de promocional paquete de panques"> %>
                      <%= image_tag "promo01_1.jpg", class: "d-block w-100", alt: 'Imagen de promocional paquete de panques', aria: { label: 'Imagen de promocional paquete de panques' } %>
                      <div class="carousel-caption d-sm-block d-md-block d-lg-block">
                        <h5>¡Especiales del mes!</h5><br>
                        <p class="des_promo">Volcán de chocolate, bizcocho de sabor intenso</p>
                        <div class="d-grid gap-2  col-sm-4 col-md-4 mx-auto">
                          <%# <button type="button" class="btn btn-dark btn-lg m-5"><a href="promos.html">Comprar</a></button> %>
                          <%= button_tag class: 'btn btn-dark btn-lg m-5' do %>
                            <%= link_to 'Comprar', not_implemented_path %> <%# implementar los ids elementos del carrousel %>
                          <% end %>
                        </div>
                      </div>
                  
                    </div>

                    <div class="carousel-item" data-bs-interval="4000">
                      <%# <img src="img/promo03.jpg" class="d-block w-100" alt="..."> %>
                      <%= image_tag 'promo03.jpg', class: 'd-block w-100', alt: '...' %>
                      <div class="carousel-caption d-sm-block d-md-block">
                        <h5>¡Especiales del mes!</h5><br>
                        <p class="des_promo">Irresistibles muffins de chocolate salvaje</p>
                        <div class="d-grid gap-2  col-sm-4 col-md-4 mx-auto">
                          <%# <button type="button" class="btn btn-dark btn-lg m-5"><a href="promos.html">Comprar</a></button> %>
                          <%= button_tag class: 'btn btn-dark btn-lg m-5' do %>
                            <%= link_to 'Comprar', not_implemented_path %> <%# implementar los ids elementos del carrousel %>
                          <% end %>
                        </div>
                      </div>
                    </div>

                    <div class="carousel-item">
                      <%# <img src="img/promo02.jpg" class="d-block w-100" alt="..."> %>
                      <%= image_tag 'promo02.jpg', class: 'd-block w-100' %>
                      <div class="carousel-caption  d-sm-block d-md-block">
                        <h5>¡Especiales del mes!</h5> <br>
                        <p class="des_promo">Tarta de chocolate y frambueas exóticas</p>
                        <div class="d-grid gap-2  col-sm-4 col-md-4 mx-auto">
                          <%# <button type="button" class="btn btn-dark btn-lg m-5" ><a href="promos.html">Comprar</a></button> %>
                          <%= button_tag class: 'btn btn-dark btn-lg m-5' do %>
                            <%= link_to 'Comprar', not_implemented_path %> <%# implementar los ids elementos del carrousel %>
                          <% end %>
                        </div>
                      </div>
                    </div>

                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
              
              </div>
            

        <!-- Fin de carrusel promocional -->


<!-- Inicia carrusel promocional movil -->
<div id="carouselExampleCaptionsM" class="carousel slide  carouselmovil d-sm-block d-md-none d-lg-none d-xl-none" data-bs-ride="false">
  <div class="carousel-indicators indicadores">
    <button type="button" data-bs-target="#carouselExampleCaptionsM" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptionsM" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptionsM" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner ">
    
    <div class="carousel-item active" data-bs-interval="4000">
      <div class="card" style="width:100%;">
        <%# <img src="img/promo01_1.jpg" class="card-img-top" alt="..."> %>
        <%= image_tag 'promo01_1.jpg', class: 'card-img-top', alt: '...' %>
        <div class="card-body">
          
            <h5 class="titulo-movil m-2">¡Especiales del mes!</h5><br>
            <p class="des_promo des_movil m-2">Volcán de chocolate, bizcocho de sabor intenso</p>
            <div class="d-grid gap-2  col-sm-6 col-md-6 mx-auto">
              <%# <button type="button" class="btn btn-dark btn-lg m-5 boton-cta"><a href="promos.html">Comprar</a></button> %>
              <%= button_tag class: 'btn btn-dark btn-lg m-5' do %>
                <%= link_to 'Comprar', not_implemented_path %> <%# implementar los ids elementos del carrousel %>
              <% end %>
            </div>
         
        </div>
      </div>
  
    </div>

    <div class="carousel-item" data-bs-interval="4000">
      <div class="card" style="width:100%;">
        <%# <img src="img/promo03.jpg" class="card-img-top" alt="..."> %>
        <%= image_tag 'promo03.jpg', class: 'card-img-top', alt: '...' %>
        <div class="card-body">
          
            <h5 class="titulo-movil m-2">¡Especiales del mes!</h5><br>
            <p class="des_promo des_movil m-2">Irresistibles muffins de chocolate salvaje</p>
            <div class="d-grid gap-2 col-sm-6 col-md-6  mx-auto">
              <%# <button type="button" class="btn btn-dark btn-lg m-5 boton-cta" ><a href="promos.html">Comprar</a> </button> %>
              <%= button_tag class: 'btn btn-dark btn-lg m-5' do %>
                <%= link_to 'Comprar', not_implemented_path %> <%# implementar los ids elementos del carrousel %>
              <% end %>
            </div>
         
        </div>
      </div>
      
    </div>

    <div class="carousel-item">
      <div class="card" style="width:100%;">
        <%# <img src="img/promo02.jpg" class="card-img-top" alt="..."> %>
        <%= image_tag 'promo02.jpg', class: 'card-img-top', alt: '...' %>
        <div class="card-body">
          
            <h5 class="titulo-movil m-2">¡Especiales del mes!</h5><br>
            <p class="des_promo des_movil m-2">Tarta de chocolate y frambueas exóticas</p>
            <div class="d-grid gap-2 col-sm-6 col-md-6  mx-auto">
              <%# <button type="button" class="btn btn-dark btn-lg m-5 boton-cta" ><a href="promos.html">Comprar</a></button> %>
              <%= button_tag class: 'btn btn-dark btn-lg m-5' do %>
                    <%= link_to 'Comprar', not_implemented_path %> <%# implementar los ids elementos del carrousel %>
              <% end %>
            </div>
         
        </div>
      </div>
      
    </div>

  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptionsM" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptionsM" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

</div>

<!-- Fin de carrusel promocional movil -->
    </main>

app/views/store/show.html.erb
<h1>Detalle de producto</h1>
<%= @product.name %>
<%= link_to 'Agregar al carrito', '/' %>

<h3>Otros productos</h3>

<%= render 'partials/index_products' %>